
# 编译器
CXX = clang++
# 输入/输出文件
INFILE = ./RServer.cpp
OUTFILE = ./mr_server

# 编译所用库
LIB = -lcurl

build:
	$(CXX) $(INFILE) -o $(OUTFILE) $(LIB)
	#sudo cp $(OUT) /bin/
	#sudo cp ./src/mr_server_boot.sh /bin/